# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5b9bbf3b-adc1-4ace-b916-7362ae4ed2e7";
      fsType = "ext4";
    };

  fileSystems."/mnt/games_1tb" =
    { device = "/dev/disk/by-uuid/E8D0407AD04050CC";
      fsType = "ntfs-3g";
      options = [ "uid=1000" "gid=100" "nofail" "umask=000" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4a7ade68-b8cf-4c82-bac7-0ef94d5a52c9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
